-- New bilingual Glow Beach Arena CMS content rows.
-- English FAQ and SEO fields without approved translations are intentionally empty strings.
-- This migration inserts only namespaced keys; legacy/test rows are not referenced or modified.
-- Re-execution aborts before inserting if any new key already exists.

DO $migration$
DECLARE
  new_keys text[] := ARRAY[
    'hero_description_lt',
    'hero_description_en',
    'arena_heading_lt',
    'arena_heading_en',
    'arena_lead_lt',
    'arena_lead_en',
    'arena_body_lt',
    'arena_body_en',
    'arena_pillar_sand_title_lt',
    'arena_pillar_sand_title_en',
    'arena_pillar_sand_description_lt',
    'arena_pillar_sand_description_en',
    'arena_pillar_light_title_lt',
    'arena_pillar_light_title_en',
    'arena_pillar_light_description_lt',
    'arena_pillar_light_description_en',
    'arena_pillar_energy_title_lt',
    'arena_pillar_energy_title_en',
    'arena_pillar_energy_description_lt',
    'arena_pillar_energy_description_en',
    'arena_pillar_events_title_lt',
    'arena_pillar_events_title_en',
    'arena_pillar_events_description_lt',
    'arena_pillar_events_description_en',
    'children_title_lt',
    'children_title_en',
    'children_description_lt',
    'children_description_en',
    'prices_children_description_lt',
    'prices_children_description_en',
    'events_heading_lt',
    'events_heading_en',
    'events_intro_lt',
    'events_intro_en',
    'company_event_title_lt',
    'company_event_title_en',
    'company_event_description_lt',
    'company_event_description_en',
    'prices_company_description_lt',
    'prices_company_description_en',
    'tournament_title_lt',
    'tournament_title_en',
    'tournament_description_lt',
    'tournament_description_en',
    'prices_heading_lt',
    'prices_heading_en',
    'prices_note_lt',
    'prices_note_en',
    'price_label_lt',
    'price_label_en',
    'price_value_on_request_lt',
    'price_value_on_request_en',
    'price_on_request_lt',
    'price_on_request_en',
    'prices_cta_lt',
    'prices_cta_en',
    'gallery_heading_lt',
    'gallery_heading_en',
    'gallery_intro_lt',
    'gallery_intro_en',
    'gallery_note_lt',
    'gallery_note_en',
    'gallery_arena_label_lt',
    'gallery_arena_label_en',
    'gallery_court_label_lt',
    'gallery_court_label_en',
    'gallery_light_label_lt',
    'gallery_light_label_en',
    'gallery_net_label_lt',
    'gallery_net_label_en',
    'gallery_sand_label_lt',
    'gallery_sand_label_en',
    'faq_reservation_question_lt',
    'faq_reservation_answer_lt',
    'faq_reservation_question_en',
    'faq_reservation_answer_en',
    'faq_court_price_question_lt',
    'faq_court_price_answer_lt',
    'faq_court_price_question_en',
    'faq_court_price_answer_en',
    'faq_kids_birthday_question_lt',
    'faq_kids_birthday_answer_lt',
    'faq_kids_birthday_question_en',
    'faq_kids_birthday_answer_en',
    'faq_company_event_question_lt',
    'faq_company_event_answer_lt',
    'faq_company_event_question_en',
    'faq_company_event_answer_en',
    'faq_tournaments_question_lt',
    'faq_tournaments_answer_lt',
    'faq_tournaments_question_en',
    'faq_tournaments_answer_en',
    'faq_location_question_lt',
    'faq_location_answer_lt',
    'faq_location_question_en',
    'faq_location_answer_en',
    'contact_phone',
    'contact_email',
    'contact_address_street',
    'contact_address_locality',
    'contact_legal_name',
    'contact_company_code',
    'contact_bank_name',
    'contact_bank_account',
    'seo_title_lt',
    'seo_title_en',
    'seo_description_lt',
    'seo_description_en',
    'seo_og_title_lt',
    'seo_og_title_en',
    'seo_og_description_lt',
    'seo_og_description_en',
    'seo_twitter_title_lt',
    'seo_twitter_title_en',
    'seo_twitter_description_lt',
    'seo_twitter_description_en'
  ];
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.site_content AS existing
    WHERE existing.key = ANY (new_keys)
  ) THEN
    RAISE EXCEPTION 'Glow Beach Arena CMS keys already exist; refusing to insert duplicates.';
  END IF;

  INSERT INTO public.site_content (key, value)
  VALUES
    ('hero_description_lt', 'Paplūdimio tinklinio arena Vilniuje'),
    ('hero_description_en', 'Beach volleyball arena in Vilnius'),
    ('arena_heading_lt', E'Ne tik aikštelė.\nVisa atmosfera.'),
    ('arena_heading_en', E'Not just a court.\nA whole atmosphere.'),
    ('arena_lead_lt', 'GLOW BEACH ARENA yra paplūdimio tinklinio arena Vilniuje, kur sportas, renginiai ir aktyvus laikas vyksta vienoje erdvėje.'),
    ('arena_lead_en', 'GLOW BEACH ARENA is a beach volleyball arena in Vilnius where sport, events and active time come together in one space.'),
    ('arena_body_lt', 'Tikras smėlis, profesionali aplinka ir išskirtinė atmosfera. Erdvė treniruotėms, varžyboms, gimtadieniams ir įmonių renginiams.'),
    ('arena_body_en', 'Real sand, a professional setting and a one-of-a-kind atmosphere. A space for training, competitions, birthdays and company events.'),
    ('arena_pillar_sand_title_lt', 'Smėlis'),
    ('arena_pillar_sand_title_en', 'Sand'),
    ('arena_pillar_sand_description_lt', 'Tikras paplūdimio jausmas'),
    ('arena_pillar_sand_description_en', 'The real beach feeling'),
    ('arena_pillar_light_title_lt', 'Šviesa'),
    ('arena_pillar_light_title_en', 'Light'),
    ('arena_pillar_light_description_lt', 'Išskirtinė arenos atmosfera'),
    ('arena_pillar_light_description_en', 'A distinctive arena atmosphere'),
    ('arena_pillar_energy_title_lt', 'Energija'),
    ('arena_pillar_energy_title_en', 'Energy'),
    ('arena_pillar_energy_description_lt', 'Sportas ir aktyvus laikas'),
    ('arena_pillar_energy_description_en', 'Sport and active time'),
    ('arena_pillar_events_title_lt', 'Renginiai'),
    ('arena_pillar_events_title_en', 'Events'),
    ('arena_pillar_events_description_lt', 'Šventės ir gimtadieniai'),
    ('arena_pillar_events_description_en', 'Parties and birthdays'),
    ('children_title_lt', 'Vaikų gimtadieniai'),
    ('children_title_en', 'Kids’ birthdays'),
    ('children_description_lt', 'Aktyvi šventė smėlyje su žaidimais ir pramogomis draugams.'),
    ('children_description_en', 'An active party in the sand with games and fun for friends.'),
    ('prices_children_description_lt', 'Aktyvi šventė smėlyje su žaidimais ir pramogomis.'),
    ('prices_children_description_en', 'An active party in the sand with games and fun.'),
    ('events_heading_lt', E'Viena arena.\nKeli formatai.'),
    ('events_heading_en', E'One arena.\nMany formats.'),
    ('events_intro_lt', 'Erdvė įvykiams: gimtadieniams, įmonių šventėms ir turnyrams.'),
    ('events_intro_en', 'Room for your occasion: birthdays, company events and tournaments.'),
    ('company_event_title_lt', 'Įmonių šventės'),
    ('company_event_title_en', 'Company events'),
    ('company_event_description_lt', 'Aktyvus ir kitoks įmonės renginys: smėlis, sportas, komandinės pramogos ir gera atmosfera.'),
    ('company_event_description_en', 'A different kind of company event: sand, sport, team activities and a great atmosphere.'),
    ('prices_company_description_lt', 'Aktyvus įmonės renginys smėlyje su sportu ir pramogomis.'),
    ('prices_company_description_en', 'An active company event in the sand with sport and fun.'),
    ('tournament_title_lt', 'Turnyrai'),
    ('tournament_title_en', 'Tournaments'),
    ('tournament_description_lt', 'Varžybos ir renginiai smėlyje įvairioms grupėms.'),
    ('tournament_description_en', 'Competitions and events in the sand for all kinds of groups.'),
    ('prices_heading_lt', 'Kainos.'),
    ('prices_heading_en', 'Prices.'),
    ('prices_note_lt', 'Galutinė kaina priklauso nuo datos, trukmės ir žmonių skaičiaus. Susisiekite tiksliam pasiūlymui.'),
    ('prices_note_en', 'The final price depends on the date, duration and number of people. Get in touch for an exact quote.'),
    ('price_label_lt', 'Kaina'),
    ('price_label_en', 'Price'),
    ('price_value_on_request_lt', 'Pagal užklausą'),
    ('price_value_on_request_en', 'On request'),
    ('price_on_request_lt', 'Kaina pagal užklausą'),
    ('price_on_request_en', 'Price on request'),
    ('prices_cta_lt', 'Gauti pasiūlymą'),
    ('prices_cta_en', 'Get a quote'),
    ('gallery_heading_lt', E'Pamatyk\nareną.'),
    ('gallery_heading_en', E'See\nthe arena.'),
    ('gallery_intro_lt', 'Smėlis, šviesa ir erdvė sportui bei renginiams Vilniuje.'),
    ('gallery_intro_en', 'Sand, light and space for sport and events in Vilnius.'),
    ('gallery_note_lt', 'Iliustracijos. Tikros arenos nuotraukos bus įkeltos netrukus.'),
    ('gallery_note_en', 'Illustrations. Real photos of the arena are coming soon.'),
    ('gallery_arena_label_lt', 'Arena'),
    ('gallery_arena_label_en', 'Arena'),
    ('gallery_court_label_lt', 'Aikštelė'),
    ('gallery_court_label_en', 'Court'),
    ('gallery_light_label_lt', 'Šviesa'),
    ('gallery_light_label_en', 'Light'),
    ('gallery_net_label_lt', 'Tinklas'),
    ('gallery_net_label_en', 'Net'),
    ('gallery_sand_label_lt', 'Smėlis'),
    ('gallery_sand_label_en', 'Sand'),
    ('faq_reservation_question_lt', 'Kaip rezervuoti aikštelę?'),
    ('faq_reservation_answer_lt', 'Parašykite rezervacija@auksma.lt arba paskambinkite +370 620 71992. Rezervaciją suderinsime pagal datą, trukmę ir žmonių skaičių.'),
    ('faq_reservation_question_en', ''),
    ('faq_reservation_answer_en', ''),
    ('faq_court_price_question_lt', 'Kiek kainuoja aikštelės nuoma?'),
    ('faq_court_price_answer_lt', 'Kaina priklauso nuo datos, trukmės, formato ir žmonių skaičiaus. Tiksliam pasiūlymui susisiekite su arena.'),
    ('faq_court_price_question_en', ''),
    ('faq_court_price_answer_en', ''),
    ('faq_kids_birthday_question_lt', 'Ar galima organizuoti vaikų gimtadienį?'),
    ('faq_kids_birthday_answer_lt', 'Taip. Arena pritaikyta aktyvioms vaikų gimtadienių šventėms smėlyje su žaidimais ir pramogomis.'),
    ('faq_kids_birthday_question_en', ''),
    ('faq_kids_birthday_answer_en', ''),
    ('faq_company_event_question_lt', 'Ar galima organizuoti įmonės renginį?'),
    ('faq_company_event_answer_lt', 'Taip. Galima organizuoti aktyvų įmonės renginį su paplūdimio tinkliniu, komandinėmis veiklomis ir laiku smėlyje.'),
    ('faq_company_event_question_en', ''),
    ('faq_company_event_answer_en', ''),
    ('faq_tournaments_question_lt', 'Ar vyksta turnyrai?'),
    ('faq_tournaments_answer_lt', 'Taip. GLOW BEACH ARENA skirta turnyrams ir kitoms varžyboms smėlyje. Dėl formato ir datos susisiekite.'),
    ('faq_tournaments_question_en', ''),
    ('faq_tournaments_answer_en', ''),
    ('faq_location_question_lt', 'Kur yra GLOW BEACH ARENA?'),
    ('faq_location_answer_lt', 'Kareivių g. 15A, Vilnius. Kontaktų skiltyje esanti adreso nuoroda atidaro vietą Google Maps.'),
    ('faq_location_question_en', ''),
    ('faq_location_answer_en', ''),
    ('contact_phone', '+370 620 71992'),
    ('contact_email', 'rezervacija@auksma.lt'),
    ('contact_address_street', 'Kareivių g. 15A'),
    ('contact_address_locality', 'Vilnius'),
    ('contact_legal_name', 'Tinklinio ir pliažinio tinklinio sporto klubas „Auksma“'),
    ('contact_company_code', '193526134'),
    ('contact_bank_name', 'AB SEB bankas'),
    ('contact_bank_account', 'LT03 7044 0600 0136 1051'),
    ('seo_title_lt', 'GLOW BEACH ARENA | Paplūdimio tinklinio arena Vilniuje'),
    ('seo_title_en', ''),
    ('seo_description_lt', 'GLOW BEACH ARENA – uždara paplūdimio tinklinio arena Vilniuje, Kareivių g. 15A. Aikštelių nuoma, treniruotės, turnyrai, vaikų gimtadieniai ir įmonių renginiai.'),
    ('seo_description_en', ''),
    ('seo_og_title_lt', 'GLOW BEACH ARENA | Paplūdimio tinklinio arena Vilniuje'),
    ('seo_og_title_en', ''),
    ('seo_og_description_lt', 'Uždara paplūdimio tinklinio arena Vilniuje. Aikštelių nuoma, treniruotės, turnyrai, gimtadieniai ir įmonių renginiai.'),
    ('seo_og_description_en', ''),
    ('seo_twitter_title_lt', 'GLOW BEACH ARENA | Paplūdimio tinklinio arena Vilniuje'),
    ('seo_twitter_title_en', ''),
    ('seo_twitter_description_lt', 'Uždara paplūdimio tinklinio arena Vilniuje. Aikštelių nuoma, treniruotės ir renginiai.'),
    ('seo_twitter_description_en', '')
    ;
END;
$migration$;
